# Generated by Django 5.2.5 on 2025-09-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_author_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.IntegerField(choices=[(1, 'Political'), (2, 'Education'), (3, 'Entertainment')], null=True, verbose_name='Category'),
        ),
    ]
